### ISSUE TITLE
bornes de départs sur routeshow

### ISSUE THREAD

**Issue by Marionade** [WildCodeSchool-2023-09/bdx-php-p3-geocode#84]
J'ai fait le trajet Bordeaux Clermont-ferrand. Je trouve qu'il y a trop de bornes de  départs de proposées au début de trajet, ça fait gribouilli sur la carte, dans l'idéal mettre que celle de bordeaux car je vois qu'il y a celles de toutes les villes aux alentours. Aussi il y a bien celles au bout de 200 km (comme demandé dans la requête), mais aucune à l'arrivée : Clermont Ferrand.

**Comment by Phalenopsis** [comment]
Je suis dessus

**Comment by Phalenopsis** [comment]
Fait,

merci Marion
