### ISSUE TITLE
admin scalpin

### ISSUE THREAD

**Issue by Marionade** [WildCodeSchool-2023-09/bdx-php-p3-geocode#88]
lorsque je clique sur le "scalpin" j'ai une page blanche qui apparaît, Nicolas, tu m'as montré la flèche grise à gauche et je conseillerais plutot que la liste s'affiche directement.

- en modifiant l'adresse d'une borne  (j'ai mis n'importe quoi) j'ai eu un message d'erreur liée à la BDD, donc pas grave en soit, le reste des modifs fonctionnent.
- lorsque je modifie les utilisateurs j'ai un message d'erreur
- d'actualités jusqu'aux rapports, je tombe sur la liste des utilisateurs

**Comment by Phalenopsis** [comment]
in progress
white page done
